export * from './genre.interface'
export * from './data.interface'
export * from './genresData.interface'
export * from './movie.interface'
export * from './videosData.inerface'
export * from './video.interface'